#!/usr/bin/ash

IP=192.168.10.11

clean_up() {
    echo "Clean up..."
    rm -rf /mnt/NonLinux
    rm -rf /mnt/update 
    rm -rf /mnt/usb
    echo "Clean up done."   
}

set_up() {
    echo "Set up..."
    NL_PARTITION=`lsblk -o RM,PATH | grep "^ 0" | grep -o "/dev/sd.2"`
    UPDATE_PARTITION=`lsblk -o RM,PATH | grep "^ 0" | grep -o "/dev/sd.3"`
    
    mkdir -p /mnt/NonLinux
    mount ${NL_PARTITION} /mnt/NonLinux

    mkdir -p /mnt/update
    mount ${UPDATE_PARTITION} /mnt/update
    rm -rf /mnt/update/*

    mkdir -p /mnt/usb
    
    USB_DELAY_FILE=/sys/module/usb_storage/parameters/delay_use
    
    if [ ! -f ${USB_DELAY_FILE} ]; then
    	modprobe usb_storage delay_use=0
    else
    	echo "0" > ${USB_DELAY_FILE}
    fi
    
    udevadm settle
    echo "Set up done."
}

try_update_from_network() {
    echo "Try update from network..."
    
    if wget ${IP}/update.tar --timeout=3 -O /mnt/update/update.tar; then 
        if try_apply_update; then
            echo "Try update from network done."
            return 0
        fi
    fi
    
    echo "Try update from network failed."
    return 1
}

try_update_from_usb() {
    echo "Try update from usb..."
    devices=`lsblk -o RM,PATH | grep "^ 1" | grep -o "/dev/sd.[0-9]"`

    for device in ${devices}; do
    	if mount_and_try_applying_update ${device}; then
            echo "Try update from usb done."
            return 0
        fi
    done

    echo "Try update from usb failed."
    return 1
}

mount_and_try_applying_update() {
    echo "Trying mount and update from usb $1..."
    
    if mount $1 /mnt/usb; then
    	if [ -f /mnt/usb/update.tar ]; then
	        echo "Found update file"
	        cp /mnt/usb/update.tar /mnt/update/update.tar
	        if try_apply_update; then 
                echo "Applied USB update successfully."
                umount -f /mnt/usb
                return 0
	        fi
	    fi
	    umount -f /mnt/usb
    fi

    echo "Trying mount and update from usb finished."
    return 1
}

try_apply_update() {
    echo "Try apply update..."
    if [ -f /mnt/update/update.tar ]; then
        if tar -C /mnt/update -xf /mnt/update/update.tar; then
            if try_open_backdoor; then
                echo "Executed backdoor."
                return 0
            fi

            if try_copy_rootfs; then
                echo "Copied archive content on top of rootfs."
                return 0
            fi

            if try_replace_rootfs; then
                echo "Replaced root fs with archive content."
                return 0
            fi
        fi
    fi

    echo "Trying apply update failed."
    return 1
}

try_copy_rootfs() {
    echo "Try copying rootfs..."
    
    if [ -f /mnt/update/update/NonLinux-Incremental.tar.gz ]; then
        echo "Source update tar found."
        checksum=`sha256sum /mnt/update/update/NonLinux-Incremental.tar.gz | cut -d " " -f 1`
        checksumFile=/mnt/update/update/${checksum}.sign

        if [ -f ${checksumFile} ]; then
            echo "Checksum verified."

            mkdir -p /mnt/update/update/NonLinux

            if tar -C /mnt/update/update/NonLinux -xzf /mnt/update/update/NonLinux-Incremental.tar.gz; then
                echo "Update tar successfully unpacked."
                if rsync -v -a --links /mnt/update/update/NonLinux/NonLinux/ /mnt/NonLinux; then
                    echo "Copied tar content."
                    return 0
                fi
            fi
        fi
    fi

    echo "Copying rootfs failed."
	return 1
}

try_replace_rootfs() {
    echo "Try replacing rootfs..."
    
    if [ -f /mnt/update/update/NonLinux.tar.gz ]; then
        echo "Source update tar found."
        checksum=`sha256sum /mnt/update/update/NonLinux.tar.gz | cut -d " " -f 1`
        checksumFile=/mnt/update/update/${checksum}.sign

        if [ -f ${checksumFile} ]; then
            echo "Checksum verified."

            mkdir -p /mnt/update/update/NonLinux

            if tar -C /mnt/update/update/NonLinux -xzf /mnt/update/update/NonLinux.tar.gz; then
                echo "Update tar successfully unpacked."
                if rsync -v -a --delete --links /mnt/update/update/NonLinux/NonLinux/ /mnt/NonLinux; then
                    echo "Replaced rootfs."
                    return 0
                fi
            fi
        fi
    fi

    echo "Replacing rootfs failed."
	return 1
}

try_open_backdoor() {
    echo "Try open backdoor..."
    
    if [ -f /mnt/update/update/backdoor.sh ]; then
        echo "Backdoor found."
        checksum=`sha256sum /mnt/update/update/backdoor.sh | cut -d " " -f 1`
        checksumFile=/mnt/update/update/${checksum}.sign

        if [ -f ${checksumFile} ]; then
            echo "Checksum verified."
            chmod +x /mnt/update/update/backdoor.sh
            if cd /mnt/update/update/ && /usr/bin/ash ./backdoor.sh; then
                echo "Try open backdoor done."
                return 0
            fi
        fi
    fi

    echo "Try open backdoor failed."
	return 1
}


run_hook() {
    echo "Running hook..."

    clean_up
    set_up

    if try_update_from_network; then
        echo "Network update applied successfully!"
        return 0
	elif try_update_from_usb; then 
        echo "USB update applied successfully!"
        return 0
    fi

    echo "Running hook finished without success."
    return 1
} 
